"use client";
import {useState} from "react";
import {ArrowUpRight,Check,ChevronRight,Database,FileCheck2,Layers3,Menu,Play,Sparkles,X,Zap} from "lucide-react";
const stages=["Raw","Understand","Clean","Normalize","Validate","Intelligence"];
const details=["CSV, JSON, spreadsheets and exports","Schema discovery and semantic profiling","Duplicates, nulls and malformed values","Consistent types, formats and naming","Rules, confidence and quality gates","Analytics-ready data and insight"];
const video="https://s3-us-west-2.amazonaws.com/coverr/mp4/Busy.mp4";
function Logo(){return <a className="brand" href="#top" aria-label="Rivu AI"><svg viewBox="0 0 330 82"><defs><linearGradient id="lg" x1="0" x2="1"><stop stopColor="#fff"/><stop offset=".5" stopColor="#4abaff"/><stop offset="1" stopColor="#a765ff"/></linearGradient></defs><text x="0" y="61" fill="url(#lg)" fontSize="59" fontWeight="700" fontFamily="-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif" letterSpacing="-5">Rivu</text><text x="222" y="61" fill="url(#lg)" fontSize="38" fontWeight="600" fontFamily="-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif">ai</text></svg></a>}
function Cube({big=false}:{big?:boolean}){return <div className={big?"cube big":"cube"}>{[1,2,3,4,5,6].map(i=><i key={i}/>)}</div>}
export default function Home(){const[menu,setMenu]=useState(false);const[stage,setStage]=useState(2);const[motion,setMotion]=useState(true);const jump=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});return <main id="top">
<div className="grain"/><nav className="nav"><Logo/><div className={menu?"links open":"links"}>{[["Product","product"],["Pipeline","pipeline"],["Quality","quality"],["About","about"]].map(([a,b])=><button key={b} onClick={()=>{setMenu(false);jump(b)}}>{a}</button>)}</div><div className="navright"><button className="navcta" onClick={()=>jump("product")}>Open product <ArrowUpRight size={15}/></button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>
<section className="hero" id="product"><div className="copy"><div className="eyebrow"><b/>AI-NATIVE DATA REFINERY</div><h1>Turn messy data <span>into intelligence.</span></h1><p>Rivu understands raw data, fixes what is broken, validates every transformation and creates a clean foundation for analytics.</p><div className="actions"><button className="primary" onClick={()=>jump("pipeline")}>Explore Rivu <ChevronRight size={18}/></button><button className="secondary" onClick={()=>setMotion(!motion)}><Play size={16}/>{motion?"Pause motion":"Play motion"}</button></div><div className="proof"><span><Check/>Original data preserved</span><span><Check/>Explainable transformations</span></div></div>
<div className={motion?"stage":"stage paused"}><div className="glow g1"/><div className="glow g2"/><div className="grid3d"/><div className="video"><video src={video} autoPlay muted loop playsInline/><div className="sheen"/></div><div className="dash"><header>LIVE REFINERY <em>● ACTIVE</em></header><div className="score"><div><small>DATA HEALTH</small><strong>98.7</strong></div><span>↑ 6.2%</span></div><div className="bars">{[65,45,82,55,93,71,98,78,91].map((n,i)=><i key={i} style={{height:n+"%"}}/>)}</div><footer><span>2.48M rows</span><span>14.8K fixes</span></footer></div><div className="tag t1">RAW<strong>2.48M</strong></div><div className="tag t2">VALIDATED<strong>98.7%</strong></div><Cube/></div></section>
<div className="ticker"><div>{[...stages,...stages].map((s,i)=><span key={i}>{s}<b>✦</b></span>)}</div></div>
<section className="section" id="pipeline"><div className="intro"><div><div className="eyebrow">THE REFINERY</div><h2>One flow.<br/><span>Every messy detail.</span></h2></div><p>From ingestion to intelligence, every stage stays visible, deterministic and explainable.</p></div><div className="cards">{stages.map((s,i)=><button key={s} className={stage===i?"card active":"card"} onClick={()=>setStage(i)}><small>0{i+1}</small><div className="icon">{i===0?<Database/>:i===1?<Sparkles/>:i===4?<FileCheck2/>:i===5?<Zap/>:<Layers3/>}</div><h3>{s}</h3><p>{details[i]}</p><ArrowUpRight className="arr" size={17}/></button>)}</div><div className="refinery"><div className="refcopy"><small>STAGE 0{stage+1}</small><h3>{stages[stage]}</h3><p>{details[stage]}. Rivu creates a traceable transformation plan before deterministic code executes it.</p><span><Check/>Before / after visibility</span><span><Check/>Confidence per transformation</span><span><Check/>Original version retained</span></div><div className="sculpture"><Cube big/><div className="scan"/><div className="core"><small>RIVU</small><b>{stages[stage].toUpperCase()}</b></div></div></div></section>
<section className="section quality" id="quality"><div className="qvisual"><div className="qdisc"><div><small>QUALITY</small><strong>98.7</strong><span>/100</span></div></div><i/><i/><i/></div><div><div className="eyebrow">QUALITY INTELLIGENCE</div><h2>Know what changed.<br/><span>Know why.</span></h2><p>Rivu does not hide transformations behind a black box. It preserves the original, records the change and gives your team context.</p><div className="metrics"><div><small>ROWS PROCESSED</small><b>2.48M</b><em>↑18.4%</em></div><div><small>ISSUES RESOLVED</small><b>14.8K</b><em>↑31.9%</em></div><div><small>DATA LOSS</small><b>0</b><em>PROTECTED</em></div></div></div></section>
<section className="section" id="about"><div className="mediaTitle"><div className="eyebrow">BUILT FOR THE MESSY MIDDLE</div><h2>Data is not a file.<br/><span>It is a system.</span></h2></div><div className="media"><div className="mediaCard wide"><video src={video} autoPlay muted loop playsInline/><label>01 <b>Understand</b></label></div><div className="mediaCard art"><div className="rings"><i/><i/><b>AI</b></div><label>02 <b>Transform</b></label></div><div className="mediaCard terminal"><span>rivu/refinery</span><b>✓ schema detected</b><b>✓ 14,802 issues resolved</b><b>✓ validation passed</b><b>→ intelligence ready</b><label>03 <b>Trust</b></label></div></div></section>
<section className="final"><div className="finalglow"/><Cube big/><div className="eyebrow">RIVU BY WATERTING</div><h2>Your data.<br/><span>Finally ready.</span></h2><p>Explore the product experience and turn raw information into a reliable intelligence layer.</p><button className="primary" onClick={()=>jump("product")}>Enter Rivu <ArrowUpRight size={18}/></button></section><footer><Logo/><span>AI-native data refinery</span><span>© 2026 WaterTing</span></footer></main>}
