"use client";
import { FormEvent,useState } from "react";
import { ArrowRight,ShieldCheck,Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import styles from "../login/login.module.css";
const API=process.env.NEXT_PUBLIC_API_URL||"http://127.0.0.1:8000/api/v1";
export default function Signup(){const router=useRouter();const [full_name,setFull]=useState("");const [username,setUsername]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(API+"/auth/signup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({full_name,username,email,password})});const d=await r.json();if(!r.ok)throw new Error(d.detail?.message||d.detail||"Signup failed");localStorage.setItem("rivu_access_token",d.tokens.access_token);localStorage.setItem("rivu_user",JSON.stringify(d.user));localStorage.setItem("rivu_org",JSON.stringify(d.organization));router.push("/dashboard")}catch(e){setError(e instanceof Error?e.message:"Signup failed")}finally{setBusy(false)}}
return <main className={styles.page}><div className={styles.glow}/><header><Link href="/" className={styles.logo}><span>R</span> Rivu<span>ai</span></Link><span className={styles.secure}><ShieldCheck size={15}/> Secure workspace</span></header><section className={styles.card}><div className={styles.kicker}><Sparkles size={14}/> START YOUR REFINERY</div><h1>Create workspace.</h1><p>Bring your messy data into a controlled, intelligence-ready environment.</p><form className={styles.form} onSubmit={submit}><label className={styles.field}>Full name<input className={styles.input} value={full_name} onChange={e=>setFull(e.target.value)} required placeholder="Your name"/></label><label className={styles.field}>Username<input className={styles.input} value={username} onChange={e=>setUsername(e.target.value)} required placeholder="company-admin"/></label><label className={styles.field}>Work email<input className={styles.input} type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@company.com"/></label><label className={styles.field}>Password<input className={styles.input} type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required placeholder="At least 8 characters"/></label>{error&&<div className={styles.error}>{error}</div>}<button className={styles.submit} disabled={busy}>{busy?"Creating…":"Create workspace"} <ArrowRight size={17}/></button></form><div className={styles.note}><ShieldCheck size={16}/> Your workspace is isolated from other organizations.</div><p style={{marginTop:20,textAlign:"center",fontSize:11}}>Already have an account? <Link href="/login" style={{color:"#a28eff"}}>Sign in</Link></p></section><footer className={styles.footer}>RIVU BY WATERTING · DATA REFINERY</footer></main>
}
