"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { Activity, ArrowUpRight, BarChart3, Database, FileCheck2, FolderKanban, LogOut, Plus, RefreshCw, ShieldCheck, Sparkles, UploadCloud, X } from "lucide-react";
import { api, clearSession, Project } from "../../lib/api";
import { useRouter } from "next/navigation";
import styles from "./dashboard.module.css";

export default function Dashboard() {
  const router = useRouter(); const [projects,setProjects]=useState<Project[]>([]); const [selected,setSelected]=useState<Project|null>(null); const [showNew,setShowNew]=useState(false); const [showUpload,setShowUpload]=useState(false); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function load(){try{const r=await api.projects();setProjects(r.projects);if(!selected&&r.projects[0])setSelected(r.projects[0]);}catch{router.replace("/login")}}
  useEffect(()=>{load()},[]);
  async function create(){if(!name.trim())return;setBusy(true);try{const p=await api.createProject({name,description});setProjects(x=>[p,...x]);setSelected(p);setShowNew(false);setName("");setDescription("");}catch(e){setMessage(e instanceof Error?e.message:"Could not create project")}finally{setBusy(false)}}
  async function upload(e:ChangeEvent<HTMLFormElement>){e.preventDefault();if(!selected||!file)return;setBusy(true);setMessage("");try{const r=await api.upload(selected.id,file);setMessage(`Uploaded ${r.dataset?.name||file.name}. Processing has started.`);setShowUpload(false);setFile(null);await load()}catch(e){setMessage(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
  function logout(){clearSession();router.replace("/login")}
  return <main className={styles.app}>
    <aside className={styles.sidebar}><div className={styles.logo}><span className={styles.mark}><i/><i/><i/><i/></span>Rivu<span>ai</span></div><div className={styles.workspace}><small>WORKSPACE</small><b>{typeof window!=="undefined"?JSON.parse(localStorage.getItem("rivu_org")||"{}")?.name||"Your workspace":"Your workspace"}</b></div><nav><button className={styles.active}><BarChart3 size={17}/>Overview</button><button><FolderKanban size={17}/>Projects</button><button><Database size={17}/>Data sources</button><button><Activity size={17}/>Pipelines</button><button><FileCheck2 size={17}/>Reports</button></nav><div className={styles.sidebarBottom}><div className={styles.secure}><ShieldCheck size={16}/><span>Protected workspace<br/><small>Access controlled</small></span></div><button onClick={logout}><LogOut size={16}/>Sign out</button></div></aside>
    <section className={styles.main}><header><div><span className={styles.eyebrow}>RIVU / WORKSPACE</span><h1>Data intelligence, <span>refined.</span></h1></div><button className={styles.user} onClick={logout}>{typeof window!=="undefined"?JSON.parse(localStorage.getItem("rivu_user")||"{}")?.full_name||"Account":"Account"}<span>↗</span></button></header>
      <div className={styles.actions}><button className={styles.primary} onClick={()=>setShowNew(true)}><Plus size={17}/> New project</button><button className={styles.secondary} disabled={!selected} onClick={()=>setShowUpload(true)}><UploadCloud size={17}/> Add data</button><button className={styles.iconBtn} onClick={load}><RefreshCw size={16}/></button></div>
      {message&&<div className={styles.notice}>{message}<button onClick={()=>setMessage("")}><X size={14}/></button></div>}
      <div className={styles.metrics}><Metric label="Projects" value={String(projects.length).padStart(2,"0")} icon={<FolderKanban/>}/><Metric label="Datasets" value={projects.reduce((a,p)=>a+p.dataset_count,0).toLocaleString()} icon={<Database/>}/><Metric label="Quality" value="—" icon={<FileCheck2/>}/><Metric label="AI insights" value="Ready" icon={<Sparkles/>}/></div>
      <section className={styles.content}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>PROJECTS</span><h2>Your data environments</h2></div><span>{projects.length} total</span></div><div className={styles.projectGrid}>{projects.length===0?<div className={styles.empty}><Database size={26}/><h3>No projects yet</h3><p>Create your first data environment and start refining.</p><button className={styles.primary} onClick={()=>setShowNew(true)}>Create project <ArrowUpRight size={15}/></button></div>:projects.map(p=><button key={p.id} className={`${styles.project} ${selected?.id===p.id?styles.selected:""}`} onClick={()=>setSelected(p)}><div className={styles.projectTop}><span className={styles.projectDot}/><small>{p.dataset_count} DATASETS</small><ArrowUpRight size={15}/></div><h3>{p.name}</h3><p>{p.description||"Data refinery workspace"}</p><div className={styles.projectFoot}><span>Ready for ingestion</span><span>→</span></div></button>)}</div></section>
      {selected&&<section className={styles.selectedPanel}><div><span className={styles.eyebrow}>SELECTED PROJECT</span><h2>{selected.name}</h2><p>{selected.description||"Add a dataset to activate profiling and the Rivu refinery."}</p></div><div className={styles.pipeline}><span>01 Ingest</span><b>→</b><span>02 Profile</span><b>→</b><span>03 Clean</span><b>→</b><span>04 Validate</span><b>→</b><span>05 Intelligence</span></div></section>}
    </section>
    {showNew&&<Modal title="Create project" close={()=>setShowNew(false)}><label>Project name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Customer data refinement" autoFocus/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What will this environment contain?"/></label><button className={styles.primary} disabled={busy} onClick={create}>{busy?"Creating…":"Create project"}<ArrowUpRight size={15}/></button></Modal>}
    {showUpload&&<Modal title="Add data" close={()=>setShowUpload(false)}><p className={styles.modalIntro}>Upload source data to <b>{selected?.name}</b>. Your original file is preserved.</p><form onSubmit={upload}><label className={styles.drop}><UploadCloud size={28}/><b>{file?file.name:"Drop a file here"}</b><span>CSV, XLSX, JSON or supported export</span><input type="file" accept=".csv,.xlsx,.xls,.json,.parquet" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><button className={styles.primary} disabled={busy||!file}>{busy?"Starting refinery…":"Upload & profile"}<ArrowUpRight size={15}/></button></form></Modal>}
  </main>
}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className={styles.metric}><div>{icon}</div><small>{label}</small><b>{value}</b></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className={styles.overlay} onMouseDown={close}><div className={styles.modal} onMouseDown={e=>e.stopPropagation()}><button className={styles.close} onClick={close}><X size={17}/></button><span className={styles.eyebrow}>RIVU / ACTION</span><h2>{title}</h2>{children}</div></div>}
