"use client";
import { ChangeEvent, useCallback, useEffect, useState } from "react";
import { Activity, ArrowUpRight, Database, Download, FileText, FolderPlus, LogOut, Moon, Plus, RefreshCw, Sparkles, Sun, UploadCloud, X, ShieldCheck } from "lucide-react";
import styles from "./dashboard.module.css";
import { authFetch } from "../../lib/api";
import BrandLogo from "../../lib/BrandLogo";
import CursorField from "../../lib/CursorField";
import ProcessingRail from "../../lib/ProcessingRail";

type Project={id:string;name:string;description?:string;dataset_count:number;color:string};
type Dataset={id:string;name:string;original_filename:string;file_format:string;status:string;current_version:number;created_at:string};
type Intelligence={dataset:{id:string;name:string;source:string;format:string;version:number};profile:{rows:number;columns:number;duplicates:number;duplicate_pct:number;nulls:number;null_pct:number};quality:{overall:number;completeness:number;validity:number;consistency:number;uniqueness:number;integrity:number};issues:any[];ai?:{headline:string;summary:string;strengths:string[];risks:string[];actions:string[];data_readiness:number};refinement?:{applied:number;failed:number;quality_delta:number}|null};
const authHeaders=()=>({Authorization:"Bearer "+(typeof window!=="undefined"?localStorage.getItem("rivu_access_token")||"":"")});

export default function Dashboard(){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<Project|null>(null),[datasets,setDatasets]=useState<Dataset[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[showNew,setShowNew]=useState(false),[name,setName]=useState(""),[uploading,setUploading]=useState(false),[message,setMessage]=useState(""),[intelligence,setIntelligence]=useState<Intelligence|null>(null),[theme,setTheme]=useState<"dark"|"light">("dark");
 useEffect(()=>{const s=localStorage.getItem("rivu_theme") as "dark"|"light"|null;if(s)setTheme(s)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("rivu_theme",theme)},[theme]);
 const selectProject=useCallback(async(p:Project)=>{setSelected(p);setIntelligence(null);try{const r=await authFetch("/projects/"+p.id,{headers:authHeaders()});if(r.status===401){location.href="/login";return}const d=await r.json();if(!r.ok)throw new Error(d.detail?.message||d.detail||"Could not load project");setDatasets(d.datasets||[])}catch(e){setError(e instanceof Error?e.message:"Could not load project.")}},[]);
 const load=useCallback(async()=>{setLoading(true);try{const r=await authFetch("/projects/",{headers:authHeaders()});if(r.status===401){location.href="/login";return}const d=await r.json();setProjects(d.projects||[]);if(d.projects?.[0])await selectProject(d.projects[0])}catch{setError("Could not reach Rivu API.")}finally{setLoading(false)}},[selectProject]);
 useEffect(()=>{void load()},[load]);
 async function openIntelligence(d:Dataset){setError("");try{const r=await authFetch("/reports/"+d.id+"/dashboard",{headers:authHeaders()});const x=await r.json();if(!r.ok)throw new Error(x.detail?.message||x.detail||"Intelligence report unavailable");setIntelligence(x)}catch(e){setError(e instanceof Error?e.message:"Could not load intelligence report.")}}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!selected)return;setUploading(true);setMessage("Uploading, profiling and preparing the refinery…");const fd=new FormData();fd.append("file",file);fd.append("name",file.name.replace(/\.[^.]+$/,""));try{const r=await authFetch("/datasets/projects/"+selected.id+"/upload",{method:"POST",headers:authHeaders(),body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail?.message||d.detail||"Upload failed");setMessage("Uploaded. Rivu is profiling the dataset…");await selectProject(selected);let n=0;const poll=async()=>{n++;await selectProject(selected);if(n<24)setTimeout(poll,1500)};setTimeout(poll,1200)}catch(e){setMessage(e instanceof Error?e.message:"Upload failed")}finally{setUploading(false);e.target.value=""}}
 async function create(){if(!name.trim())return;const r=await authFetch("/projects/",{method:"POST",headers:{...authHeaders(),"Content-Type":"application/json"},body:JSON.stringify({name})});if(r.ok){setName("");setShowNew(false);await load()}else{const d=await r.json().catch(()=>({}));setError(d.detail?.message||d.detail||"Could not create project.")}}
 async function downloadReport(id:string,n:string){try{const r=await authFetch("/reports/"+id+"/pdf",{headers:authHeaders()});if(!r.ok)throw new Error("Could not generate report");const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="rivu-"+n.replace(/[^a-z0-9_-]+/gi,"-")+"-report.pdf";a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"Could not generate report")}}
 function logout(){localStorage.clear();location.href="/login"}
 return <main className={styles.app}><CursorField/><aside className={styles.sidebar}><BrandLogo href="/" className={styles.brand}/><div className={styles.workspaceLabel}>DATA WORKSPACE</div><nav><a className={styles.active} href="#overview"><Activity size={16}/>Overview</a><a href="#datasets"><Database size={16}/>Datasets</a><a href="#intelligence"><Sparkles size={16}/>Intelligence</a><a href="#reports"><FileText size={16}/>Reports</a></nav><div className={styles.sideFoot}><div className={styles.secure}><ShieldCheck size={14}/>Private workspace</div><button onClick={logout}><LogOut size={15}/>Sign out</button></div></aside>
 <section className={styles.main}><header className={styles.topbar}><div><div className={styles.eyebrow}>RIVU / DATA REFINERY</div><h1>Your data, refined.</h1><p>Upload messy data. Rivu profiles it, cleans it and turns it into decision-ready intelligence.</p></div><div className={styles.headerActions}><button className={styles.iconBtn} onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun size={16}/>:<Moon size={16}/>}</button><button className={styles.iconBtn} onClick={()=>void load()}><RefreshCw size={15}/></button><button className={styles.primary} onClick={()=>setShowNew(true)}><Plus size={16}/> New project</button></div></header>
 {error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.message}>{message}</div>}<ProcessingRail active={uploading} label="Refining dataset"/>
 <section id="overview" className={styles.kpis}><Kpi label="Projects" value={projects.length}/><Kpi label="Datasets" value={projects.reduce((a,p)=>a+p.dataset_count,0)}/><Kpi label="Refinery" value="AI ready"/><Kpi label="Security" value="Isolated"/></section>
 <section id="datasets" className={styles.workspace}><div className={styles.projectPane}><div className={styles.sectionTitle}><span>PROJECTS</span><button onClick={()=>setShowNew(true)}><Plus size={14}/></button></div>{loading?<div className={styles.muted}>Loading workspace…</div>:projects.map(p=><button key={p.id} className={selected?.id===p.id?styles.projectSelected:styles.project} onClick={()=>selectProject(p)}><i style={{background:p.color||"#6657d9"}}>R</i><span><b>{p.name}</b><small>{p.dataset_count} datasets</small></span><ArrowUpRight size={14}/></button>)}</div>
 <div className={styles.dataPane}><div className={styles.sectionTitle}><div><span>DATASETS</span><b>{selected?.name||"Select a project"}</b></div>{selected&&<label className={styles.upload}><UploadCloud size={15}/>{uploading?"Uploading…":"Upload data"}<input type="file" accept=".csv,.json,.xlsx,.xls,.parquet" onChange={upload} disabled={uploading}/></label>}</div>{selected&&<div className={styles.drop}><UploadCloud size={22}/><div><b>Drop a dataset to refine</b><small>CSV · XLSX · JSON · Parquet · up to 500 MB</small></div><label>Browse<input type="file" accept=".csv,.json,.xlsx,.xls,.parquet" onChange={upload}/></label></div>}<div className={styles.datasetList}>{datasets.map(d=><div className={styles.dataset} key={d.id}><div className={styles.file}><FileText size={16}/></div><div className={styles.datasetName}><b>{d.name}</b><small>{d.original_filename} · v{d.current_version}</small></div><span className={d.status==="transformed"?styles.ready:styles.status}>{d.status}</span><button onClick={()=>openIntelligence(d)}>Inspect <ArrowUpRight size={13}/></button></div>)}</div></div></section>
 <section id="intelligence" className={styles.reportShell}><div className={styles.reportHead}><div><div className={styles.eyebrow}>LIVE DATA INTELLIGENCE</div><h2>{intelligence?intelligence.ai?.headline||"Dataset intelligence":"Select a dataset to inspect"}</h2><p>{intelligence?intelligence.ai?.summary||"Measured quality and AI analysis.":"Quality, refinement impact and AI analysis in one operational view."}</p></div>{intelligence&&<button className={styles.primary} onClick={()=>location.href="/dashboard/dataset/"+intelligence.dataset.id}>Open full report <ArrowUpRight size={15}/></button>}</div>
 {intelligence?<div className={styles.reportGrid}><div className={styles.scoreCard}><span>DATA READINESS</span><strong>{Math.round(intelligence.ai?.data_readiness||intelligence.quality.overall)}</strong><small>/ 100</small><div className={styles.progress}><i style={{width:(intelligence.ai?.data_readiness||intelligence.quality.overall)+"%"}}/></div></div><MetricCard label="ROWS" value={intelligence.profile.rows.toLocaleString()} note={intelligence.profile.columns+" columns"}/><MetricCard label="QUALITY" value={intelligence.quality.overall.toFixed(1)} note={intelligence.refinement&&intelligence.refinement.quality_delta!==0?((intelligence.refinement.quality_delta>0?"+":"")+intelligence.refinement.quality_delta.toFixed(1)+" after refinement"):"current score"}/><MetricCard label="ISSUES" value={intelligence.issues.length} note={intelligence.profile.null_pct.toFixed(1)+"% null cells"}/><div className={styles.aiPanel}><div><h3>AI assessment</h3><p>{intelligence.ai?.summary}</p></div><div className={styles.aiLists}><List title="Strengths" items={intelligence.ai?.strengths||[]}/><List title="Risks" items={intelligence.ai?.risks||[]}/><List title="Next actions" items={intelligence.ai?.actions||[]}/></div></div><div className={styles.qualityPanel}><h3>Quality dimensions</h3>{Object.entries(intelligence.quality).map(([k,v])=><Bar key={k} label={k} value={Number(v)}/>)}</div></div>:<div className={styles.emptyReport}><Sparkles size={25}/><b>Pick a dataset above</b><span>See measured quality, AI findings and refinement impact here.</span></div>}</section>
 <section id="reports" className={styles.reportStrip}><div><div className={styles.eyebrow}>REPORT CENTER</div><h2>Decision-ready reports</h2><p>Open the live intelligence report or download a branded PDF.</p></div><div className={styles.reportActions}>{datasets.slice(0,4).map(d=><div key={d.id}><b>{d.name}</b><button onClick={()=>downloadReport(d.id,d.name)}><Download size={13}/> PDF</button></div>)}</div></section>
 {showNew&&<div className={styles.modal}><div className={styles.modalCard}><button className={styles.close} onClick={()=>setShowNew(false)}><X size={17}/></button><div className={styles.eyebrow}>NEW PROJECT</div><h2>Create a data workspace.</h2><p>Keep sources, refined versions and intelligence history together.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Customer Data Refinery" onKeyDown={e=>e.key==="Enter"&&create()}/><button className={styles.primaryWide} onClick={create}><FolderPlus size={16}/> Create project</button></div></div>}</section></main>
}
function Kpi({label,value}:{label:string;value:string|number}){return <div className={styles.kpi}><span>{label}</span><b>{value}</b></div>}
function MetricCard({label,value,note}:{label:string;value:string|number;note:string}){return <div className={styles.metricCard}><span>{label}</span><b>{value}</b><small>{note}</small></div>}
function Bar({label,value}:{label:string;value:number}){return <div className={styles.bar}><div><span>{label}</span><b>{value.toFixed(1)}</b></div><i><em style={{width:Math.max(0,Math.min(100,value))+"%"}}/></i></div>}
function List({title,items}:{title:string;items:string[]}){return <div><h4>{title}</h4>{items.length?items.slice(0,3).map((x,i)=><p key={i}>• {x}</p>):<p className={styles.muted}>None reported</p>}</div>}